// test generated by openai

package svc

import "testing"

func TestDoTheNeedful(t *testing.T) {
	tests := []struct {
		name   string
		person Person
		want   string
	}{
		{name: "Test young person", person: Person{Name: "Alice", Age: 25}, want: "young"},
		{name: "Test old person", person: Person{Name: "Bob", Age: 50}, want: "old"},
		{name: "Test middle-aged person", person: Person{Name: "Charlie", Age: 40}, want: "young"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := DoTheNeedful(tt.person)
			if got != tt.want {
				t.Errorf("DoTheNeedful() = %v, want %v", got, tt.want)
			}
		})
	}
}
