package svc

import (
	"errors"
	"fmt"
	"go-make-tests/internal/colors"
	"log"
	"strings"
)

type AskForTestConfig struct {
	Language  string
	Framework string
	CodeInput string
	OutFile   string
}

func (a *AskForTestConfig) Set(i int, value string) {
	if i > 3 {
		panic(errors.New("trying to set ask for test config out of range"))
	}
	if i == 0 {
		a.Language = value
	}
	if i == 1 {
		a.Framework = value
	}
	if i == 2 {
		a.CodeInput = value
	}
	if i == 3 {
		a.OutFile = value
	}
}

type TestGenIface interface {
	AskForTest(AskForTestConfig) error
}

type TestGen struct {
	chatService ChatServiceIface
	fileService FileServiceIface
}

func NewTestGen(chatService ChatServiceIface, fileService FileServiceIface) TestGenIface {
	return &TestGen{chatService: chatService, fileService: fileService}
}

func (tg *TestGen) AskForTest(conf AskForTestConfig) error {
	prompt := getPrompt(conf.Language, conf.Framework)

	tg.chatService.Prompt(prompt)
	log.Println(colors.Blue("Asking AI..."))
	result, err := tg.chatService.InvokeUserQuery(conf.CodeInput)

	if err != nil {
		return err
	}

	processed := processContent(result.Content, conf.Language)

	if err := tg.fileService.SaveFile(conf.OutFile, processed); err != nil {
		return err
	}

	resultToStdOut(processed)
	return nil
}

func getPrompt(language, framework string) string {
	return fmt.Sprintf(
		`You are an expert %s programmer.
		Given the provided code, please write a unit test for it in the %s testing framework.
		Try to achieve total code coverage.
		Only return the code.`, language, framework)
}

func processContent(content, language string) string {
	cleanedContent := strings.Replace(content, fmt.Sprintf("```%s", language), "// test generated by openai\n", 1)
	return strings.Replace(cleanedContent, "```", "", 1)
}

func resultToStdOut(result string) {
	log.Println(colors.Green("Success"))
	log.Println(result)
}
